### ISSUE TITLE
设置代理有问题

### ISSUE THREAD

**Issue by fewpiwork** [wnanbei/direwolf#3]
![image](https://user-images.githubusercontent.com/32926982/73370946-f861d700-42ef-11ea-9ad0-88b52319be32.png)

**Comment by fewpiwork** [comment]
http不带s的可以访问  带s的不行

![image](https://user-images.githubusercontent.com/32926982/73371314-7aea9680-42f0-11ea-8f87-b4d4da205793.png)

**Comment by fewpiwork** [comment]
抱歉 曲解了意思..原来要这样用 `分别为HTTP/HTTPS设置代理`
直观的意思我以为是 传入一个HTTP/HTTPS协议的代理...

![image](https://user-images.githubusercontent.com/32926982/73372564-6a3b2000-42f2-11ea-9fdb-90e93dcad146.png)

**Comment by wnanbei** [comment]
对，HTTP和HTTPS字段是分别为不同的协议设置不同的代理。
使用哪种代理只与代理proxy的url有关。
新年快乐
