### ISSUE TITLE
请求支持session所有cookie tostring

### ISSUE THREAD

**Issue by fewpiwork** [wnanbei/direwolf#4]
RT..用于保存 下次登录

**Comment by wnanbei** [comment]
目前 direwolf 使用的是 Go 标准库中的 Cookiejar，其并没有提供获取所有 Cookie 的接口，所以实现这个功能需要更多的工作。
大多数情况下用户是获取某个域名的所有 Cookie。这个功能使用 Session 的 `Cookies` 方法即可，返回的是 `Cookie` 类型的一个 Slice，而 `Cookie` 类型本身有 `String` 这个方法，遍历切片，调用这个方法即可。

**Comment by wnanbei** [comment]
如果没有疑问，我会在两天后关闭这个 issue。
